spring:
  application:
    name: 'user-service-api'
  data:
    mongodb:
      uri: mongodb+srv://helpdesk:helpdesk@cluster0.9arjcny.mongodb.net/helpdeskdb?retryWrites=true&w=majority
      auto-index-creation: true
Springdoc:
  openapi:
    title: 'User Service API'
    description: 'Document for User Sevice API'
    version: '1.0.0'