spring:
  application:
        name: 'auth-server-api'
  data:
    mongodb:
      uri: mongodb+srv://helpdesk:helpdesk@cluster0.9arjcny.mongodb.net/helpdeskdb?retryWrites=true&w=majority

jwt.secret: 'Kh6aI4AQHR/p9WpEWtgNjsoUazlCSIFrNS48p+G9zdKy7PWugF9Wk1DByooGBbFFaCVVchcunmSMiik5dDTd3VnX/vyPcfjdTaGDIEpVc7k='
jwt.expiration: 120000
jwt.expiration-sec.refresh-token: 10

server:
  port: ${SERVER_PORT:8081}
